[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"

[dependencies.bitburner_bindings]
path = "../bindings"

[lib]
crate-type = ["cdylib"]

